import sys
import json
import anthropic
from fastmcp import FastMCP
from starlette.requests import Request
from starlette.responses import JSONResponse

sys.path.insert(0, '.')
from config import Config

mcp = FastMCP("DecisionSynthesis MCP Server")

_anthropic_client = anthropic.Anthropic(api_key=Config.ANTHROPIC_API_KEY) if Config.ANTHROPIC_API_KEY else None


def _rule_based_decision(
    credit_score: int,
    debt_to_income_ratio: float,
    employment_risk: str,
    loan_amount_risk: str,
    income_stability_score: float,
) -> dict:
    risk_score = 0
    factors = []

    if credit_score < 650:
        risk_score += 30
        factors.append("Low credit score")
    elif credit_score < 700:
        risk_score += 15
        factors.append("Below-average credit score")

    if debt_to_income_ratio > 0.5:
        risk_score += 25
        factors.append("High debt-to-income ratio")
    elif debt_to_income_ratio > 0.4:
        risk_score += 10
        factors.append("Moderate debt-to-income ratio")

    if employment_risk == "High":
        risk_score += 20
        factors.append("Employment risk flagged")
    elif employment_risk == "Medium":
        risk_score += 5

    if loan_amount_risk == "High":
        risk_score += 20
        factors.append("High loan amount relative to income")

    if income_stability_score < 50:
        risk_score += 15
        factors.append("Low income stability")

    risk_score = min(risk_score, 100)

    if risk_score > 70:
        classification = "Reject"
        confidence = 0.95
    elif risk_score > 45:
        classification = "Review"
        confidence = 0.7
    else:
        classification = "Approve"
        confidence = 0.9 if risk_score < 30 else 0.75

    explanation = (
        f"Decision based on credit score ({credit_score}), "
        f"DTI ratio ({debt_to_income_ratio:.2f}), "
        f"and employment status ({employment_risk}). "
        f"Risk score: {risk_score}"
    )

    return {
        "classification": classification,
        "risk_score": risk_score,
        "confidence_level": confidence,
        "key_decision_factors": factors,
        "explanation": explanation,
    }


def _claude_decision(
    applicant_id: str,
    credit_score: int,
    credit_score_risk_level: str,
    debt_to_income_ratio: float,
    employment_risk: str,
    loan_amount: float,
    income: float,
    loan_amount_risk: str,
    income_stability_score: float,
) -> dict:
    prompt = f"""You are a loan underwriting AI. Analyze the following applicant risk profile and provide a structured loan decision.

Applicant Risk Profile:
- Credit Score: {credit_score} (Risk Level: {credit_score_risk_level})
- Debt-to-Income Ratio: {debt_to_income_ratio:.2f}
- Employment Risk: {employment_risk}
- Loan Amount: ${loan_amount:,.2f}
- Annual Income: ${income:,.2f}
- Loan Amount Risk: {loan_amount_risk}
- Income Stability Score: {income_stability_score:.1f}/100

Based on this profile, provide your decision as valid JSON with exactly these fields:
{{
  "classification": "<Approve|Review|Reject>",
  "risk_score": <integer 0-100>,
  "confidence_level": <float 0.0-1.0>,
  "key_decision_factors": ["<factor1>", "<factor2>", ...],
  "explanation": "<2-3 sentence business narrative explaining the decision>"
}}

Rules:
- Approve: low-risk applicant, risk_score 0-45
- Review: borderline applicant requiring manual review, risk_score 46-70
- Reject: high-risk applicant, risk_score 71-100
- key_decision_factors must list the top factors that drove the decision
- explanation must read as a professional underwriter's narrative, not a template

Respond with only the JSON object, no other text."""

    response = _anthropic_client.messages.create(
        model=Config.MODEL_NAME,
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    parsed = json.loads(raw)

    classification = parsed.get("classification", "Review")
    if classification not in ("Approve", "Review", "Reject"):
        classification = "Review"

    risk_score = max(0, min(100, int(parsed.get("risk_score", 50))))
    confidence = max(0.0, min(1.0, float(parsed.get("confidence_level", 0.7))))

    factors = parsed.get("key_decision_factors", [])
    if not isinstance(factors, list):
        factors = [str(factors)]

    explanation = str(parsed.get("explanation", "Decision generated by Claude."))

    return {
        "classification": classification,
        "risk_score": risk_score,
        "confidence_level": confidence,
        "key_decision_factors": factors,
        "explanation": explanation,
    }


@mcp.tool()
def synthesize_decision(
    applicant_id: str,
    income_stability_score: float,
    employment_risk: str,
    debt_to_income_ratio: float,
    credit_score: int,
    credit_score_risk_level: str,
    loan_amount_risk: str,
    loan_amount: float,
    income: float,
) -> dict:
    """Synthesize a loan decision using Claude AI with rule-based fallback."""
    result = None

    if _anthropic_client is not None:
        try:
            result = _claude_decision(
                applicant_id=applicant_id,
                credit_score=credit_score,
                credit_score_risk_level=credit_score_risk_level,
                debt_to_income_ratio=debt_to_income_ratio,
                employment_risk=employment_risk,
                loan_amount=loan_amount,
                income=income,
                loan_amount_risk=loan_amount_risk,
                income_stability_score=income_stability_score,
            )
        except Exception:
            result = None

    if result is None:
        result = _rule_based_decision(
            credit_score=credit_score,
            debt_to_income_ratio=debt_to_income_ratio,
            employment_risk=employment_risk,
            loan_amount_risk=loan_amount_risk,
            income_stability_score=income_stability_score,
        )

    return {"applicant_id": applicant_id, **result}


# Legacy HTTP shim
@mcp.custom_route("/tools/synthesize_decision", methods=["POST"])
async def _http_synthesize_decision(request: Request) -> JSONResponse:
    body = await request.json()
    result = synthesize_decision(
        applicant_id=body.get("applicant_id", ""),
        income_stability_score=body.get("income_stability_score", 70.0),
        employment_risk=body.get("employment_risk", "Low"),
        debt_to_income_ratio=body.get("debt_to_income_ratio", 0.0),
        credit_score=body.get("credit_score", 700),
        credit_score_risk_level=body.get("credit_score_risk_level", "Low"),
        loan_amount_risk=body.get("loan_amount_risk", "Low"),
        loan_amount=body.get("loan_amount", 0.0),
        income=body.get("income", 1.0),
    )
    return JSONResponse(result)


@mcp.custom_route("/health", methods=["GET"])
async def _health(request: Request) -> JSONResponse:
    return JSONResponse({"status": "healthy", "service": "DecisionSynthesis"})


app = mcp.http_app()

if __name__ == "__main__":
    import asyncio
    asyncio.run(mcp.run_http_async(host="0.0.0.0", port=8003, show_banner=False))
